type: opencv

source: 0 # rtsp://192.168.0.194:554/onvif1

# resolution:
#   width: 640
#   height: 320
# fps: 30

convert_to_rgb: true

# type: mock

# source:
#   type: video # video | dir
#   path: datasets/video/sample.mp4

# resolution:
#   width: 640
#   height: 320

# fps: 30
