type: ui

# type: mock

# requests:
#     - label: "apple"
#       timestamp: 1767521105.7700403

#     - label: "banana"
#       timestamp: 1767521106.7700403

#     - label: "orange"
#       timestamp: 1767521107.7700403
