type: mock

results:
  - is_match: true
    confidence: 0.95
    detected_label: "apple"

  - is_match: true
    confidence: 0.64
    detected_label: "banana"

  - is_match: false
    confidence: 0.87
    detected_label: "grape"

  - is_match: true
    confidence: 0.87

  - is_match: false
    detected_label: "orange"

  - is_match: false

# type: ui
